import type { NextConfig } from "next";
import { PHASE_DEVELOPMENT_SERVER } from "next/constants";
import createNextIntlPlugin from "next-intl/plugin";

const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");

/**
 * The `connect-src` entry MUST be an origin (`scheme://host[:port]`), never
 * a URL with a path. Per the CSP3 source-expression matching algorithm, a
 * source whose path does not end in `/` requires an EXACT path match — so a
 * path-bearing value like `https://api.scripe.org/api` would allow requests
 * to that literal `/api` path only and block every other path under it
 * (e.g. `/api/v1/auth/signup/pricing-context`, which
 * `src/lib/pricing/pricing-context.ts` actually fetches). The documented
 * production value of `NEXT_PUBLIC_API_BASE_URL` (`.env.example`) IS
 * path-bearing (`https://api.scripe.org/api`), so the header must derive
 * just the origin from it rather than interpolating the raw env value.
 * `new URL(...).origin` does that regardless of whether the configured base
 * carries a path, and keeps this fallback aligned with
 * `pricing-context.ts`'s own fallback (`https://api.scripe.org/api`) — both
 * now resolve to the same origin instead of silently diverging.
 */
const apiOrigin = new URL(process.env.NEXT_PUBLIC_API_BASE_URL ?? "https://api.scripe.org/api").origin;

const securityHeaders = [
  { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=(), payment=()" },
  {
    key: "Content-Security-Policy",
    value: [
      "default-src 'self'",
      "script-src 'self' 'unsafe-inline'",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data:",
      "font-src 'self'",
      `connect-src 'self' ${apiOrigin}`,
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
    ].join("; "),
  },
];

/**
 * Phase-based config, not a plain object — see the `distDir` property below
 * for why. Next calls this with `(phase, { defaultConfig })` (`phase` is one
 * of the `PHASE_*` constants from `next/constants`, derived from the actual
 * CLI command that invoked Next) and accepts a returned object or Promise —
 * `server/config-shared.js`'s `normalizeConfig()` awaits whatever comes
 * back, so wrapping the result in `withNextIntl()` before returning it is
 * fine even though that call is synchronous.
 *
 * @param phase - Which Next.js command is loading this config.
 * @returns The resolved config for `next-intl`'s plugin to further wrap.
 */
export default function nextConfig(phase: string): NextConfig {
  const config: NextConfig = {
    /**
     * `next dev` and `next build`/`next start` must never share one output
     * directory. Next's own dev server already nests its per-process state a
     * layer deeper (`{distDir}/dev/...`) than a production build, but both
     * still read/write the SAME top-level `{distDir}/cache` (webpack/turbopack
     * persistent cache, image-optimization cache) by default — a `next build`
     * running while a stray `next dev` is still alive on the same checkout
     * corrupts that shared cache and can leave a production `.next` missing
     * its manifests (observed: `.next/server` + `.next/cache` present with no
     * `BUILD_ID`/`static`, from exactly this collision). Giving dev its own
     * top-level directory removes the shared cache entirely.
     *
     * This branches on `phase`, not `NODE_ENV`: Next only APPLIES its own
     * `NODE_ENV` default (`"development"` for `next dev`, `"production"` for
     * `next build`/`next start`) when the variable is unset going in. An
     * inherited `NODE_ENV=development` — common under Docker/PM2/self-host
     * process managers that export it globally — survives untouched, so
     * `next start` would read `.next-dev` under the old `NODE_ENV` check and
     * crash with "Could not find a production build" even though a real
     * `.next` build exists right next to it. `phase` has no such failure
     * mode: it is derived from which `next` subcommand is actually running,
     * never from a mutable environment variable.
     */
    distDir: phase === PHASE_DEVELOPMENT_SERVER ? ".next-dev" : ".next",
    images: {
      // AVIF first (best compression), WebP fallback for browsers/paths that
      // skip AVIF — Next negotiates via the request's `Accept` header and
      // serves the original format for anything that accepts neither.
      formats: ["image/avif", "image/webp"],
    },
    async headers() {
      return [
        { source: "/:path*", headers: securityHeaders },
        // Wave K: every file under public/media/ is generated by
        // scripts/build-media-assets.mjs from assets/ (see that script's own
        // header) and changes only via an explicit, deliberate content
        // operation — never per-deploy, per-request, or per-user. With no
        // Cache-Control set, Next's default for a plain public/ file is
        // effectively "revalidate every time" (observed: `max-age=0`), which
        // forces a conditional round-trip for the hero's own background
        // plate on every single page load, reload included — the "images
        // take time, especially on reload" report this closes.
        //
        // NOT `immutable`: these filenames are stable across a content swap
        // (assets/README.md's whole naming convention is "the same name
        // survives a replaced photo"), so a returning visitor genuinely
        // could be served a week-old file after one. 7 days with a 1-day
        // stale-while-revalidate window is the deliberate trade: it removes
        // the round-trip for every practical repeat-visit pattern (same
        // session, same day, same week) while still self-correcting within
        // days if an image is ever swapped without also renaming it.
        { source: "/media/:path*", headers: [{ key: "Cache-Control", value: "public, max-age=604800, stale-while-revalidate=86400" }] },
      ];
    },
  };

  return withNextIntl(config);
}
