/* ============================================================================
   SCRIPE — Arabic (ar)

   Authored Arabic, not a mirrored English sentence. The meaning, the hierarchy
   and the restraint of the English copy are kept; the phrasing is written to
   read naturally to an Arabic operations director. No marketing claim is added
   that the English does not already make.

   Latin product names (SCRIPE), sport names already used in Latin form, sample
   figures, currency amounts and initials are deliberately left as they are.
   ========================================================================= */
window.SCRIPE_AR = {
  /* ── global chrome: navigation, controls, footer ───────────────────────── */
  "nav.platform": "المنصة",
  "nav.solutions": "الحلول",
  "nav.pricing": "الأسعار",
  "nav.resources": "المصادر",
  "nav.company": "الشركة",
  "nav.contact": "تواصل معنا",
  "nav.bookDemo": "احجز عرضًا توضيحيًا",
  "nav.home": "SCRIPE — الرئيسية",
  "nav.openMenu": "افتح القائمة",
  "nav.closeMenu": "أغلق القائمة",
  "nav.allSolutions": "كل الحلول",
  "nav.megaMeta": "منصة واحدة — أربع طرق لتنظيم الرياضة",
  "nav.primary": "التنقل الرئيسي",
  "nav.siteNav": "تنقل الموقع",
  "nav.skip": "تخطَّ إلى المحتوى",

  "ui.theme.label": "المظهر",
  "ui.theme.toDark": "التبديل إلى المظهر الداكن",
  "ui.theme.toLight": "التبديل إلى المظهر الفاتح",
  "ui.lang.label": "اللغة",
  "ui.lang.toArabic": "التبديل إلى العربية",
  "ui.lang.toEnglish": "Switch to English",
  "ui.lang.en": "EN",
  "ui.lang.ar": "ع",

  "footer.tagline": "نظام تشغيل المنظمات الرياضية الحديثة",
  "footer.socialNote": "لم تُنشر قنوات التواصل بعد.",
  "footer.platformOverview": "نظرة عامة على المنصة",
  "footer.membersSubs": "الأعضاء والاشتراكات",
  "footer.reservationsPayments": "الحجوزات والمدفوعات",
  "footer.reportsAnalytics": "التقارير والتحليلات",
  "footer.aboutScripe": "عن SCRIPE",
  "footer.privacy": "الخصوصية",
  "footer.terms": "الشروط",

  "pricing.perYear": "سنويًا · لكل فرع",

  /* Authored line breaks are part of these headlines, so they are translated
     as markup rather than plain text — the break lands where it should in
     Arabic too, and English restores with its breaks intact. */
  "platform.headline": "كل ما تحتاجه منظمتك الرياضية.<br/>نظام تشغيل واحد.",
  "mso.headline": "فروع متعددة.<br/>رياضات متعددة.<br/>صورة تشغيلية واحدة.",


  "form.err.name": "أخبرنا من أنت.",
  "form.err.nameLong": "هذا الاسم طويل جدًا.",
  "form.err.email": "نحتاج عنوانًا نرد عليه.",
  "form.err.emailInvalid": "يبدو أن البريد الإلكتروني غير مكتمل.",
  "form.err.emailLong": "عنوان البريد الإلكتروني طويل جدًا.",
  "form.err.org": "لأي منظمة هذا الطلب؟",
  "form.err.orgLong": "اسم المنظمة طويل جدًا.",
  "form.err.phoneLong": "رقم الهاتف طويل جدًا.",
  "form.err.messageLong": "الرسالة طويلة جدًا.",
  "form.err.network": "تعذّر الإرسال الآن. حاول مرة أخرى بعد قليل.",
  "form.thanks": "شكرًا لك، {name}.",
  "form.thanksFallback": "شكرًا لك.",
  "form.demoNotice":
    "سجّلنا بياناتك. هذا الموقع غير متصل بعد ببريد مباشر — إلى أن يتصل، أرسل البيانات نفسها إلى جهة الاتصال لديك في SCRIPE وسيتابعها أحد مسؤولي التشغيل.",
  "form.another": "أرسل طلبًا آخر",
  "form.sending": "جارٍ الإرسال…",

  /* ── page copy ─────────────────────────────────────────────────────────── */
  "09-00-alexandria": "٠٩:٠٠ · الإسكندرية",
  "1-add-branches": "١ (أضف فروعًا)",
  "1-hour-ago": "قبل ساعة",
  "11-subscriptions-renew-this-week": "١١ اشتراكًا تتجدد هذا الأسبوع.",
  "12-min-ago": "قبل ١٢ دقيقة",
  "124-this-month": "+١٢٤ هذا الشهر",
  "14-00-olympic-pool": "١٤:٠٠ · المسبح الأولمبي",
  "17-30-main-stadium": "١٧:٣٠ · الملعب الرئيسي",
  "19-00-courts-1-3": "١٩:٠٠ · الملاعب ١–٣",
  "2-months": "−شهران",
  "3-hours-ago": "قبل ٣ ساعات",
  "3-open": "٣ مفتوحة",
  "3-surfaces-2-860-members": "٣ ملاعب · ٢٬٨٦٠ عضوًا",
  "33-of-enquiries": "٣٣٪ من الاستفسارات",
  "34-vs-last-season": "+٣٤٪ مقارنة بالموسم الماضي",
  "4-surfaces-1-880-members": "٤ ملاعب · ١٬٨٨٠ عضوًا",
  "4-surfaces-2-540-members": "٤ ملاعب · ٢٬٥٤٠ عضوًا",
  "5-surfaces-5-120-members": "٥ ملاعب · ٥٬١٢٠ عضوًا",
  "9-surfaces-in-use": "٩ ملاعب قيد الاستخدام",
  "97-marked": "٩٧٪ مُسجَّل",
  "a-30-minute-call-with-an-operations": "مكالمة من ٣٠ دقيقة مع مسؤول تشغيل، لا نص محفوظ",
  "a-dedicated-guardian-portal-is-planned-not": "بوابة مخصصة لأولياء الأمور مخطط لها، لم تُطلق بعد",
  "a-haddad": "أ. حداد",
  "a-haddad-technical-u12-u14": "أ. حداد · فني تحت ١٢–١٤",
  "a-plan-confirmed-with-your-team-before": "خطة مؤكدة مع فريقك قبل توقيع أي شيء",
  "a-reference-for-every-module": "مرجع لكل وحدة.",
  "a-sports-operations-system-members-programs-sessions":
    "نظام تشغيل رياضي. الأعضاء والبرامج والحصص والملاعب والحجوزات والمدفوعات والتقارير تعمل على سجل واحد متصل بدل أدوات منفصلة.",
  "absences-reach-guardians-without-a-phone-call": "الغياب يصل إلى ولي الأمر دون مكالمة هاتفية",
  academies: "الأكاديميات",
  "academy-day-tuesday": "يوم الأكاديمية · الثلاثاء",
  "academy-led": "بقيادة الأكاديمية",
  "academy-pitch-1-60-min": "ملعب الأكاديمية ١ · ٦٠ دقيقة",
  "academy-pitch-2-90-min": "ملعب الأكاديمية ٢ · ٩٠ دقيقة",
  "academy-pitches-gym-hall": "ملاعب الأكاديمية، صالة رياضية",
  "academy-term-guardian-linked": "فصل دراسي بالأكاديمية · مرتبط بولي الأمر",
  "academy-term-u14": "فصل الأكاديمية · تحت ١٤",
  active: "نشط",
  "active-members": "الأعضاء النشطون",
  alexandria: "الإسكندرية",
  "alexandria-76": "الإسكندرية · ٧٦٪",
  "all-branches": "كل الفروع",
  analytics: "التحليلات",
  articles: "المقالات",
  "ask-the-question-directly-an-operations-lead":
    "اطرح سؤالك مباشرة — سيجيب عليه أحد مسؤولي التشغيل، وغالبًا ما يصبح الدليل التالي.",
  athletes: "اللاعبون",
  "athletes-guardians-coaches-programs-sessions-surface":
    "اللاعبون وأولياء الأمور والمدربون والبرامج والحصص والملاعب والحجوزات والمدفوعات تشترك في سجل واحد. لا شيء يُدخل مرتين، ولا شيء يُطابَق مرتين.",
  attendance: "الحضور",
  "attendance-and-reminders": "الحضور والتذكيرات",
  "attendance-by-sport": "الحضور حسب الرياضة",
  "attendance-closed-the-same-day-it-happened": "الحضور يُغلق في اليوم نفسه الذي حدث فيه",
  "attendance-marked": "الحضور المُسجَّل",
  "attendance-marked-present": "الحضور مُسجَّل · حاضر",
  "attendance-progression-and-trial-evidence-read-toget":
    "الحضور والتقدّم وأدلة الاختبارات تُقرأ معًا عبر مسار التطوير.",
  "attendance-this-week": "الحضور · هذا الأسبوع",
  "attendance-tracked": "تتبّع الحضور",
  automation: "الأتمتة",
  availability: "الإتاحة",
  "availability-one-off-and-recurring-booking-pricing":
    "الإتاحة والحجز المفرد والمتكرر وقواعد التسعير وتسجيل الدخول على شبكة واحدة.",
  "availability-one-off-and-recurring-booking-pricing-0af4":
    "الإتاحة والحجز المفرد والمتكرر وقواعد التسعير وتسجيل الدخول ومعدل الاستخدام في ساعات الذروة.",
  "back-to-home": "العودة إلى الرئيسية",
  basketball: "كرة السلة",
  "basketball-development": "تطوير كرة السلة",
  "before-you-talk-to-sales": "قبل أن تتحدث إلى المبيعات.",
  "billing-period": "دورة الفوترة",
  "board-level-reporting-built-from-the-record":
    "تقارير على مستوى مجلس الإدارة تُبنى من السجل بدل إعادة إدخالها في عرض تقديمي.",
  "book-a-demo": "احجز عرضًا توضيحيًا",
  "book-a-demo-a83d": "احجز عرضًا توضيحيًا",
  "book-a-demo-of-your-own-operation": "احجز عرضًا توضيحيًا على تشغيلك أنت.",
  booked: "محجوز",
  "booked-to-capacity-not-to-chaos": "محجوزة بالكامل، لا بالفوضى.",
  bookings: "الحجوزات",
  "bookings-this-week": "حجوزات هذا الأسبوع",
  "branch-level-timetables-staff-and-pricing": "جداول وطواقم وتسعير على مستوى الفرع",
  "branch-management": "إدارة الفروع",
  branches: "الفروع",
  "branches-included": "الفروع المشمولة",
  breadcrumb: "مسار التنقل",
  "bring-every-branch-and-every-sport-onto":
    "اجمع كل فرع وكل رياضة على خط تقارير واحد — بصلاحيات محددة ومطابقة في اليوم نفسه.",
  "bring-the-branches-sports-and-season-volume":
    "أحضر الفروع والرياضات وحجم الموسم الذي تديره فعليًا. سنُريك أين يناسبك SCRIPE — وأين لا يناسبك.",
  "bring-the-operation-you-actually-run-we":
    "أحضر التشغيل الذي تديره فعليًا. سنُريك أين يناسبك SCRIPE وأين لا يناسبك.",
  "bring-your-branch-count-sports-and-season":
    "أحضر عدد فروعك ورياضاتك وحجم موسمك — وسنؤكد الخطة قبل توقيع أي شيء.",
  "bring-your-programmes-groups-and-guardians-into":
    "اجمع برامجك ومجموعاتك وأولياء الأمور في إيقاع تشغيلي واحد — نُعدّه مع فريقك قبل أن تجربه.",
  "bring-your-teams-members-venues-coaches-and":
    "اجمع فرقك وأعضاءك ومنشآتك ومدربيك وعملياتك في منصة واحدة قوية.",
  "business-insights": "رؤى الأعمال",
  "business-intelligence": "ذكاء الأعمال",
  cairo: "القاهرة",
  "cairo-94": "القاهرة · ٩٤٪",
  "cairo-sports-club": "نادي القاهرة الرياضي",
  "can-coaches-use-scripe": "هل يمكن للمدربين استخدام SCRIPE؟",
  "can-i-manage-different-sports": "هل يمكنني إدارة رياضات مختلفة؟",
  "can-i-manage-multiple-branches": "هل يمكنني إدارة عدة فروع؟",
  "can-i-manage-reservations-and-payments": "هل يمكنني إدارة الحجوزات والمدفوعات؟",
  "can-parents-access-the-platform": "هل يمكن لأولياء الأمور الدخول إلى المنصة؟",
  "can-t-find-what-you-need": "لم تجد ما تبحث عنه؟",
  capabilities: "القدرات",
  "category-placeholders-replace-with-partner-marks-onc":
    "عناوين فئات مؤقتة — تُستبدل بشعارات الشركاء بعد الاعتماد.",
  "centralized-operations": "تشغيل مركزي",
  "centralized-operations-across-branches-and-sports-co":
    "تشغيل مركزي عبر الفروع والرياضات: مؤشرات مجمّعة، وإدارة فروع، وصلاحيات محددة، وتقارير على مستوى المجموعة، وذكاء الأعمال الذي يقرأها كلها معًا.",
  "centralized-operations-combined-kpis-branch-manageme":
    "تشغيل مركزي، ومؤشرات مجمّعة، وإدارة فروع، وصلاحيات، وتقارير على مستوى المجموعة.",
  "charged-on-the-rule-that-fits-the": "يُحتسب وفق القاعدة المناسبة للحصة.",
  "charges-invoices-and-reconciliation-attached-to-the":
    "الرسوم والفواتير والمطابقة مرتبطة بما جرى حجزه فعلًا.",
  "check-in-at-reception-or-on-the": "تسجيل الدخول في الاستقبال أو من الهاتف",
  "choose-a-solution": "اختر حلًا",
  "choose-your-shape": "اختر شكل منظمتك",
  "club-operations": "تشغيل النادي",
  clubs: "الأندية",
  "clubs-academies-venues-and-multi-branch-organization":
    "الأندية والأكاديميات والمنشآت والمنظمات متعددة الفروع — الملّاك والمديرون ومسؤولو التشغيل والمدربون وموظفو الاستقبال.",
  "clubs-academies-venues-and-multi-sports-organization":
    "الأندية والأكاديميات والمنشآت والمنظمات متعددة الرياضات تدير أيامًا مختلفة. لكنها تعمل على السجل نفسه.",
  "coach-cover-needed-for-u16-position-trials": "مطلوب مدرب بديل لاختبارات المراكز تحت ١٦.",
  "coach-load-balanced-against-real-session-counts": "حمل المدربين موزون على عدد الحصص الفعلي",
  "coach-load-sessions-per-week": "حمل المدربين · حصص أسبوعيًا",
  "coach-load-share-of-weekly-sessions": "حمل المدربين · نصيبه من حصص الأسبوع",
  "coach-management": "إدارة المدربين",
  "coach-management-74f7": "إدارة المدربين",
  "coach-marks-the-roster-from-the-phone": "المدرب يسجّل القائمة من هاتفه",
  "coach-notified": "إشعار المدرب",
  coaches: "المدربون",
  coastal: "ساحلي",
  collected: "محصّل",
  "combined-kpis": "مؤشرات مجمّعة",
  "combined-kpis-for-the-organization-not-five": "مؤشرات مجمّعة للمنظمة، لا خمسة ملفات تصدير",
  "coming-soon": "قريبًا",
  commercial: "تجاري",
  communication: "التواصل",
  company: "الشركة",
  "company-website": "الموقع الإلكتروني للشركة",
  compare: "قارن",
  "compare-all-four-solutions": "قارن الحلول الأربعة",
  "compare-plans": "قارن الخطط",
  comparison: "المقارنة",
  "competition-calendar": "روزنامة المسابقات",
  competitions: "المسابقات",
  "competitions-and-squads": "المسابقات والفرق",
  confirmed: "مؤكد",
  contact: "تواصل معنا",
  "conversion-visible-per-sport-and-per-branch": "معدل التحويل ظاهر لكل رياضة ولكل فرع",
  converted: "تحوّل إلى عضوية",
  corporate: "شركات",
  "corporate-pitch-1": "شركات · ملعب ١",
  "court-1-tuesday": "ملعب ١ · الثلاثاء",
  courts: "الملاعب",
  "courts-fields-and-pools-booked-to-capacity": "ملاعب وميادين ومسابح محجوزة بالكامل، لا بالفوضى.",
  "courts-fields-and-pools-with-real-availability":
    "ملاعب وميادين ومسابح بإتاحة حقيقية، وحجوزات مفردة ومتكررة، وقواعد تسعير، ومدفوعات، وأرقام الاستخدام التي تحدد الموسم القادم.",
  "courts-fields-pools-reservations-and-utilization": "ملاعب وميادين ومسابح وحجوزات ومعدل استخدام.",
  "cover-requests-and-cancellations-raised-immediately": "طلبات البدلاء والإلغاءات تُرفع فورًا",
  "cover-requests-raised-and-resolved-before-kick": "طلبات البدلاء تُرفع وتُحل قبل صافرة البداية",
  crm: "إدارة العلاقات",
  "crm-and-notifications": "إدارة العلاقات والإشعارات",
  custom: "حسب الطلب",
  "custom-roles-and-permissions": "أدوار وصلاحيات مخصصة",
  "dashboard-updated": "تحديث لوحة التشغيل",
  "development-is-a-programme-not-a-timetable": "التطوير برنامج، لا جدول مواعيد.",
  "development-programs": "برامج التطوير",
  "development-programs-coaches-parents-and-athletes-in":
    "برامج التطوير والمدربون وأولياء الأمور واللاعبون في إيقاع واحد.",
  "development-programs-parents-and-coach-management": "برامج التطوير وأولياء الأمور وإدارة المدربين",
  "each-branch-keeps-its-own-timetable-and":
    "كل فرع يحتفظ بجدوله وطاقمه. وتقارير المجموعة تقرأ عبرها جميعًا دون سجلات مكررة.",
  "each-branch-runs-its-own-timetable-staff":
    "كل فرع يدير جدوله وطاقمه وتسعيره — دون تكرار سجل عضو واحد.",
  "each-solution-is-the-same-platform-configured":
    "كل حل هو المنصة نفسها، مهيّأة حول التشغيل الذي تديره بالفعل.",
  "eleven-a-side-five-a-side-and":
    "ملاعب ١١ لاعبًا والخماسي والتدريب، محجوزة مع المدرب والتوقيت في خطوة واحدة.",
  email: "البريد الإلكتروني",
  enquiries: "الاستفسارات",
  "enquiries-captured-from-reception-phone-and-web": "الاستفسارات تُلتقط من الاستقبال والهاتف والموقع",
  "enquiries-trials-and-follow-ups-tracked-to":
    "الاستفسارات والاختبارات والمتابعات مُتتبَّعة حتى تتحول إلى عضوية.",
  enterprise: "المؤسسات",
  "evening-demand-moved-earlier-across-padel-and":
    "الطلب المسائي انتقل إلى وقت أبكر في البادل والخماسي. أُعيد توزيع مدربَيْن لتغطية الذروة الجديدة.",
  "every-branch-runs-its-own-day-the":
    "كل فرع يدير يومه. والمجموعة تقرأ صورة تشغيلية واحدة عبرها جميعًا.",
  "every-module-resolves-into-one-dashboard": "كل وحدة تنتهي إلى لوحة تشغيل واحدة.",
  "every-notice-traces-back-to-the-record": "كل إشعار يعود إلى السجل الذي أطلقه",
  "every-plan-is-confirmed-with-your-operations":
    "كل خطة تُؤكَّد مع فريق التشغيل لديك قبل التوقيع. والنسخ التجريبية تُعدّ مع فريقنا لتُربط برامجك وملاعبك وطاقمك قبل أن تجربها.",
  "every-plan-runs-on-the-same-record":
    "كل خطة تعمل على السجل نفسه. الفارق هو مقدار ما تغطيه من التشغيل.",
  "every-renewal-visible-before-it-lands-not": "كل تجديد ظاهر قبل استحقاقه، لا بعده",
  "every-session-booking-and-payment-is-already":
    "كل حصة وحجز ودفعة هي أصلًا نقطة بيانات. وSCRIPE يقرأها معًا.",
  "every-session-pitch-and-athlete-on-one": "كل حصة وكل ملعب وكل لاعب على إيقاع تشغيلي واحد",
  "every-solution-can-run-every-module-these":
    "كل حل يمكنه تشغيل كل وحدة. هذه هي التي تعتمد عليها كل منظمة أولًا.",
  "everything-in-growth": "كل ما في خطة النمو",
  "everything-in-starter": "كل ما في خطة البداية",
  "everything-worth-reading-before-you-decide": "كل ما يستحق القراءة قبل أن تقرر.",
  "everything-your-sports-organization-needs": "كل ما تحتاجه منظمتك الرياضية.",
  "everything-your-sports-organization-needs-one-operat": "كل ما تحتاجه منظمتك الرياضية. نظام تشغيل واحد.",
  "evidence-that-survives-the-season-it-was": "أدلة تبقى بعد الموسم الذي جُمعت فيه",
  "explore-multi-sports-organizations": "استكشف المنظمات متعددة الرياضات",
  "explore-scripe-for-multi-sports-organizations": "استكشف SCRIPE للمنظمات متعددة الرياضات",
  "explore-scripe-for-multi-sports-organizations-fd71": "استكشف SCRIPE للمنظمات متعددة الرياضات",
  "explore-scripe-for-sports-academies": "استكشف SCRIPE للأكاديميات الرياضية",
  "explore-scripe-for-sports-clubs": "استكشف SCRIPE للأندية الرياضية",
  "explore-scripe-for-sports-venues": "استكشف SCRIPE للمنشآت الرياضية",
  "explore-sports-academies": "استكشف الأكاديميات الرياضية",
  "explore-sports-clubs": "استكشف الأندية الرياضية",
  "explore-sports-venues": "استكشف المنشآت الرياضية",
  "explore-the-platform": "استكشف المنصة",
  "exportable-without-a-data-project": "قابلة للتصدير دون مشروع بيانات",
  "family-and-sibling-pricing-without-manual-maths": "تسعير العائلة والإخوة دون حسابات يدوية",
  fields: "الميادين",
  "first-team": "الفريق الأول",
  "first-team-set-pieces": "الفريق الأول · الكرات الثابتة",
  "five-a-side": "الخماسي",
  "five-a-side-2-padel-courts": "ملعب خماسي، ملعبا بادل",
  "five-a-side-60-min": "خماسي · ٦٠ دقيقة",
  "five-a-side-pitch-a": "خماسي · ملعب A",
  "fixture-calendar-shared-with-coaches-and-guardians": "روزنامة المباريات مشتركة مع المدربين وأولياء الأمور",
  "fixtures-squads-travel-and-results-kept-on":
    "المباريات والفرق والتنقلات والنتائج على الروزنامة نفسها التي يقرأها بقية النادي.",
  "fixtures-this-month": "مباريات هذا الشهر",
  "fixtures-travel-and-availability-on-the-calendar":
    "المباريات والتنقلات والإتاحة على الروزنامة التي يتابعها المدربون وأولياء الأمور أصلًا.",
  flagship: "الفرع الرئيسي",
  focus: "التركيز",
  "follow-ups-owned-by-a-person-with": "متابعات لكل منها مسؤول وتاريخ",
  football: "كرة القدم",
  "football-clubs": "أندية كرة القدم",
  "football-intelligence": "ذكاء كرة القدم",
  "football-intelligence-evidence": "أدلة ذكاء كرة القدم",
  "football-pathway": "مسار كرة القدم",
  "for-growing-clubs-and-venues": "للأندية والمنشآت النامية.",
  "for-multi-branch-organizations": "للمنظمات متعددة الفروع.",
  "for-small-academies": "للأكاديميات الصغيرة.",
  "four-things-we-hold-to": "أربعة مبادئ نلتزم بها.",
  "four-ways-sport-is-organized-one-system": "أربع طرق لتنظيم الرياضة. نظام واحد تحتها.",
  fri: "الجمعة",
  "friday-block-6-weeks": "بلوك الجمعة · ٦ أسابيع",
  "from-the-member-app-or-reception": "من تطبيق العضو أو من الاستقبال.",
  "front-desk": "الاستقبال",
  "get-a-plan-scoped-to-your-operation": "احصل على خطة مفصّلة على تشغيلك.",
  "getting-rosters-session-plans-and-offline-attendance":
    "إيصال القوائم وخطط الحصص وتسجيل الحضور دون إنترنت إلى أيدي المدربين.",
  "glass-courts-indoor-halls-and-outdoor-surfaces":
    "ملاعب زجاجية وصالات مغلقة وملاعب مكشوفة، لكل منها قواعده وتسعيره.",
  "go-deeper-on-reports-and-analytics": "تعمّق في التقارير والتحليلات",
  group: "المجموعة",
  "group-reporting-without-duplicate-member-records": "تقارير المجموعة دون سجلات أعضاء مكررة",
  "group-revenue": "إيرادات المجموعة",
  "group-revenue-membership-attendance-and-utilization":
    "إيرادات المجموعة والعضويات والحضور ومعدل الاستخدام على سطر واحد، لا خمسة ملفات تصدير.",
  "group-view": "عرض المجموعة",
  "group-view-tuesday": "عرض المجموعة · الثلاثاء",
  growth: "النمو",
  "guardian-contacts-linked-to-every-athlete-record": "بيانات ولي الأمر مرتبطة بكل سجل لاعب",
  "guardian-portal-on-the-roadmap": "بوابة أولياء الأمور ضمن خارطة الطريق",
  "guardians-receive-session-and-attendance-updates-tod":
    "يتلقى أولياء الأمور تحديثات الحصص والحضور اليوم. أما البوابة المخصصة لهم فهي ضمن خارطة الطريق لا الإصدار الحالي.",
  "guardians-receive-session-attendance-and-payment-upd":
    "يتلقى أولياء الأمور تحديثات الحصص والحضور والمدفوعات دون مكالمة هاتفية.",
  "guardians-receive-the-session-attendance-and-payment":
    "يتلقى أولياء الأمور تحديثات الحصص والحضور والمدفوعات التي كانت تصل سابقًا بمكالمة هاتفية.",
  "guest-booking-60-min": "حجز ضيف · ٦٠ دقيقة",
  "guided-setup": "إعداد موجَّه",
  guides: "الأدلة",
  "guides-are-in-preparation-ask-for-the":
    "الأدلة قيد الإعداد. اطلب الموضوع الذي تحتاجه وسنرسله فور كتابته.",
  "gym-hall-60-min": "الصالة الرياضية · ٦٠ دقيقة",
  gymnastics: "الجمباز",
  "gymnastics-development": "الجمباز · التطوير",
  "h-kamal": "ح. كمال",
  "hamza-kamal-u14": "حمزة كمال · تحت ١٤",
  held: "محجوز مؤقتًا",
  "held-slots-release-automatically-when-payment-does": "المواعيد المحجوزة تُفرج تلقائيًا إذا لم تصل الدفعة.",
  "held-slots-release-when-payment-does-not":
    "المواعيد المحجوزة تُفرج إذا لم تصل الدفعة؛ والمدفوعة تُطابَق في اليوم نفسه.",
  "highlighted-insight": "رؤية مميزة",
  "history-that-survives-a-change-of-branch": "سجل يبقى رغم تغيّر الفرع أو الرياضة",
  home: "الرئيسية",
  "home-and-away-logistics-attached-to-the": "ترتيبات الذهاب والإياب مرتبطة بالمباراة",
  "how-many-branches-which-sports-and-what": "كم فرعًا، وأي رياضات، وما الذي تعمل عليه اليوم.",
  "how-organizations-set-scripe-up": "كيف تُعِدّ المنظمات SCRIPE.",
  "how-pricing-works": "كيف يعمل التسعير",
  "how-programs-groups-and-sessions-are-structured":
    "كيف تُبنى البرامج والمجموعات والحصص قبل استيراد أول عضو.",
  "how-we-build": "كيف نبني",
  "in-preparation": "قيد الإعداد",
  "in-session": "حصة جارية",
  included: "مشمول",
  "includes-onboarding-with-your-operations-team": "يشمل التهيئة مع فريق التشغيل لديك.",
  "indicative-pricing-every-plan-is-confirmed-with":
    "أسعار استرشادية — كل خطة تُؤكَّد مع فريق التشغيل لديك قبل التوقيع.",
  intelligence: "الذكاء",
  intro: "المقدمة",
  "invoices-receipts-and-outstanding-balances-tied-to":
    "الفواتير والإيصالات والأرصدة المستحقة مرتبطة بالبرنامج، لا بدفتر حسابات.",
  "invoices-receipts-and-refunds-from-the-same": "الفواتير والإيصالات والمستردات من السجل نفسه",
  "is-there-a-free-trial": "هل توجد نسخة تجريبية مجانية؟",
  "k-nasser": "ك. ناصر",
  "k-nasser-trials-and-selection": "ك. ناصر · الاختبارات والانتقاء",
  "l-farah": "ل. فرح",
  "l-farah-swimming-squad": "ل. فرح · فريق السباحة",
  "lanes-squad-blocks-and-public-swim-managed":
    "الحارات وبلوكات الفريق والسباحة العامة تُدار على الشبكة نفسها مثل كل شيء آخر.",
  "layla-farouk": "ليلى فاروق",
  "leave-a-number-in-the-form-and": "اترك رقمك في النموذج وسنتصل بك.",
  "m-osman": "م. عثمان",
  "m-osman-small-sided-u14": "م. عثمان · ملاعب مصغّرة تحت ١٤",
  maadi: "المعادي",
  "maadi-88": "المعادي · ٨٨٪",
  "main-stadium": "الملعب الرئيسي",
  "main-stadium-120-min": "الملعب الرئيسي · ١٢٠ دقيقة",
  "main-stadium-75-min": "الملعب الرئيسي · ٧٥ دقيقة",
  "main-stadium-pool-3-padel-courts": "الملعب الرئيسي، مسبح، ٣ ملاعب بادل",
  "make-the-operation-the-easiest-part-of": "اجعل التشغيل أسهل جزء في إدارة الرياضة.",
  "many-branches": "فروع متعددة.",
  "many-branches-many-sports-one-operational-picture": "فروع متعددة، رياضات متعددة، صورة تشغيلية واحدة",
  "mapping-your-programs-into-scripe": "ربط برامجك داخل SCRIPE",
  "marked-at-the-session-offline-capable-and":
    "يُسجَّل في الحصة، ويعمل دون إنترنت، ويُغلق في اليوم نفسه الذي حدث فيه.",
  "marked-pitchside-in-seconds-offline-if-the":
    "يُسجَّل بجانب الملعب في ثوانٍ، ودون إنترنت إن لم تكن هناك تغطية — ويُغلق في اليوم نفسه.",
  "marked-pitchside-in-seconds-offline-when-the":
    "يُسجَّل بجانب الملعب في ثوانٍ، ودون إنترنت عند انقطاع التغطية، ويُغلق في اليوم نفسه.",
  "marked-pitchside-offline-if-needed": "يُسجَّل بجانب الملعب، ودون إنترنت عند الحاجة.",
  "matchweek-tuesday": "أسبوع المباريات · الثلاثاء",
  "medical-notes-documents-and-consents-attached": "الملاحظات الطبية والمستندات والموافقات مرفقة",
  "member-booking-90-min": "حجز عضو · ٩٠ دقيقة",
  "member-books-training": "العضو يحجز تدريبًا",
  "member-guest-and-recurring-pricing-on-courts": "تسعير الأعضاء والضيوف والحجز المتكرر للملاعب والميادين وحارات المسبح.",
  "member-receives-reminder": "العضو يتلقى تذكيرًا",
  "member-record": "سجل العضو",
  members: "الأعضاء",
  "members-and-profiles": "الأعضاء والملفات",
  "members-and-subscriptions": "الأعضاء والاشتراكات",
  "members-this-month": "أعضاء هذا الشهر",
  "membership-attendance-revenue-and-squad-availability":
    "العضوية والحضور والإيرادات وجاهزية الفريق على مجموعة تعريفات واحدة.",
  message: "الرسالة",
  mission: "الرسالة",
  mon: "الاثنين",
  "mon-17-30-main-stadium": "الاثنين ١٧:٣٠ · الملعب الرئيسي",
  monday: "الاثنين",
  monthly: "شهريًا",
  "most-chosen": "الأكثر اختيارًا",
  "most-organizations-are-more-than-one-we":
    "معظم المنظمات أكثر من شكل واحد. نحدد ذلك مع فريق التشغيل لديك قبل تهيئة أي شيء.",
  "moving-a-season-mid-year": "نقل موسم في منتصف العام",
  "multi-branch": "تعدد الفروع",
  "multi-branch-control-and-reporting": "تحكم وتقارير متعددة الفروع",
  "multi-sport-by-default": "متعدد الرياضات بطبيعته",
  "multi-sports-organization": "منظمة متعددة الرياضات",
  "multi-sports-organizations": "المنظمات متعددة الرياضات",
  "multi-sports-organizations-d792": "المنظمات متعددة الرياضات",
  "multiple-branches": "فروع متعددة",
  "multiple-branches-multiple-sports-one-operational-pi": "فروع متعددة، رياضات متعددة، صورة تشغيلية واحدة.",
  "multiple-sports": "رياضات متعددة",
  "n-zaki": "ن. زكي",
  name: "الاسم",
  "nasr-city": "مدينة نصر",
  "nasr-city-81": "مدينة نصر · ٨١٪",
  "needs-coach": "يحتاج مدربًا",
  "next-7-days": "الأيام السبعة القادمة",
  "no-back-catalogue-no-invented-case-studies":
    "لا أرشيف سابق، ولا دراسات حالة مُختلقة. يمتلئ هذا القسم بعد الإطلاق.",
  "not-a-manifesto-the-constraints-the-product": "ليست بيانًا — بل القيود التي صُمم المنتج عليها فعلًا.",
  "not-found": "غير موجود",
  "not-included": "غير مشمول",
  "not-published-yet": "لم يُنشر بعد",
  "not-sure-which-shape-you-are": "لست متأكدًا أي شكل يناسبك؟",
  "notes-on-running-sport": "ملاحظات في إدارة الرياضة",
  "nothing-in-this-sequence-needs-a-person": "لا شيء في هذا التسلسل يحتاج أن يتذكره أحد.",
  notifications: "الإشعارات",
  "observations-and-trial-notes-reach-selection-without":
    "الملاحظات وتقارير الاختبارات تصل إلى الانتقاء دون إعادة كتابة",
  "offline-capable-where-the-pitch-has-no":
    "يعمل دون إنترنت حيث لا تغطية في الملعب، وسريع حيث الاستقبال مزدحم، وهادئ حيث التشغيل يسير بالفعل.",
  "olympic-pool": "المسبح الأولمبي",
  "olympic-pool-75-min": "المسبح الأولمبي · ٧٥ دقيقة",
  "omar-darwish": "عمر درويش",
  onboarding: "التهيئة",
  "onboarding-notes": "ملاحظات التهيئة",
  "one-booking-sets-off-the-whole-chain":
    "حجز واحد يُطلق السلسلة كاملة — الحجز، الدفع، القائمة، التذكير، الحضور، التقرير.",
  "one-booking-sets-off-the-whole-chain-022f": "حجز واحد يُطلق السلسلة كاملة.",
  "one-channel-to-guardians-and-coaches-traceable":
    "قناة واحدة لأولياء الأمور والمدربين، يمكن تتبعها إلى السجل الذي أطلقها.",
  "one-connected-record": "سجل واحد متصل",
  "one-definition-of-a-session-a-member": "تعريف واحد للحصة وللعضو وللدفعة، مُطبَّق في كل مكان.",
  "one-member-record-across-sports-squads-and": "سجل عضو واحد عبر الرياضات والفرق والفروع",
  "one-off-and-recurring-bookings-that-survive":
    "حجوزات مفردة ومتكررة تصمد أمام تعارض مباراة أو نافذة صيانة.",
  "one-operating-system-module-by-module": "نظام تشغيل واحد، وحدةً وحدة.",
  "one-operational-picture": "صورة تشغيلية واحدة",
  "one-operational-picture-across-branches-and-sports": "صورة تشغيلية واحدة عبر الفروع والرياضات",
  "one-organization": "منظمة واحدة",
  "one-organization-4-branches": "منظمة واحدة · ٤ فروع",
  "one-organization-every-branch-one-operational-pictur": "منظمة واحدة. كل فرع. صورة تشغيلية واحدة.",
  "one-place-the-numbers-agree": "مكان واحد تتفق فيه الأرقام.",
  "one-platform-for-clubs-academies-venues-and":
    "منصة واحدة للأندية والأكاديميات والمنشآت والمنظمات متعددة الرياضات.",
  "one-record-per-athlete-carried-across-groups": "سجل واحد لكل لاعب، ينتقل عبر المجموعات والرياضات والمواسم.",
  "one-record-per-athlete-guardian-and-staff":
    "سجل واحد لكل لاعب وولي أمر وموظف — ينتقل عبر كل فرع ورياضة وموسم.",
  "one-record-read-by-every-module-not": "سجل واحد تقرأه كل وحدة — لا أربع نسخ في أربع أدوات.",
  "one-reporting-line": "خط تقارير واحد",
  open: "مفتوح",
  "open-notifications": "إشعارات مفتوحة",
  "open-pause-or-restructure-a-branch-without": "افتح فرعًا أو أوقفه أو أعد هيكلته دون إعادة بناء المنظمة حوله.",
  "operating-picture": "الصورة التشغيلية",
  operations: "التشغيل",
  "operations-answered-before-anyone-has-to-ask": "أسئلة التشغيل مُجابة قبل أن يسألها أحد",
  "operations-overview": "نظرة عامة على التشغيل",
  "optional-helps-us-reach-you-faster": "اختياري — يساعدنا على الوصول إليك أسرع.",
  "optional-it-tells-us-which-modules-to": "اختياري — يخبرنا أي الوحدات نعرضها أولًا.",
  organization: "المنظمة",
  "organized-differently-the-system-underneath-is-the": "منظمة بشكل مختلف؟ النظام تحتها هو نفسه.",
  "other-solutions": "حلول أخرى",
  "outstanding-balances-visible-per-member-and-per": "الأرصدة المستحقة ظاهرة لكل عضو ولكل فرع",
  padel: "البادل",
  "padel-98-sold": "البادل · بيع ٩٨٪",
  "padel-clubs": "أندية البادل",
  "padel-court-1": "بادل · ملعب ١",
  "padel-court-2": "بادل · ملعب ٢",
  "padel-courts": "ملاعب البادل",
  "padel-courts-are-the-first-surface-to":
    "ملاعب البادل أول ما ينفد كل أسبوع. ويبقى موعدان من خمسة مواعيد مسائية في الملعب ٢ دون بيع.",
  "padel-member-guest-access": "عضو بادل · دخول ضيف",
  "padel-members-night": "ليلة أعضاء البادل",
  paid: "مدفوع",
  parents: "أولياء الأمور",
  "patterns-you-would-not-see-on-a":
    "أنماط لا تراها في جدول مواعيد: ساعات الذروة، والمواعيد غير المباعة، والرياضات التي تحمل الأسبوع.",
  paused: "متوقف مؤقتًا",
  "payment-recorded": "تسجيل الدفعة",
  "payment-recorded-against-the-session-not-a": "الدفعة تُسجَّل على الحصة، لا على صف في جدول",
  "payment-reminders-before-the-due-date-not": "تذكيرات الدفع قبل تاريخ الاستحقاق، لا بعده",
  payments: "المدفوعات",
  "payments-and-invoices": "المدفوعات والفواتير",
  "payments-reconciled-against-what-was-actually-booked": "المدفوعات مُطابَقة مع ما جرى حجزه فعلًا",
  "peak-booking-hours-increased-by-18": "ارتفعت ساعات الحجز في الذروة بنسبة ١٨٪.",
  "peak-hour-demand": "الطلب في ساعات الذروة",
  "peak-hour-demand-tracked-across-surfaces-and": "الطلب في الذروة مُتتبَّع عبر الملاعب والرياضات",
  "peak-hours": "ساعات الذروة",
  "peak-hours-unsold-capacity-and-coach-load":
    "ساعات الذروة والطاقة غير المباعة وحمل المدربين، مقارنةً عبر المجموعة كاملة.",
  "per-branch-per-sport-per-season-same": "لكل فرع، ولكل رياضة، ولكل موسم — التعريفات نفسها في كل مكان",
  "per-month-per-branch": "شهريًا · لكل فرع",
  performance: "الأداء",
  permissions: "الصلاحيات",
  phone: "الهاتف",
  "pick-the-shape-that-matches-your-organization": "اختر الشكل الذي يطابق منظمتك — والسجل تحته هو نفسه.",
  "pipeline-this-month": "المسار · هذا الشهر",
  "pitch-2": "الملعب ٢",
  "pitch-2-61-sold": "الملعب ٢ · بيع ٦١٪",
  "pitch-2-90-min": "الملعب ٢ · ٩٠ دقيقة",
  planned: "مخطط له",
  platform: "المنصة",
  "pool-lane-4-maintenance-closes-thursday-06": "صيانة الحارة ٤ في المسبح تُغلقها الخميس ٠٦:٠٠.",
  "pool-lanes-1-2": "المسبح · الحارتان ١–٢",
  "pool-tennis-basketball": "مسبح، تنس، كرة سلة",
  pools: "المسابح",
  "position-trials-u14": "اختبارات المراكز · تحت ١٤",
  "priced-around-branches-sports-and-volume": "التسعير على أساس الفروع والرياضات والحجم.",
  "priced-per-branch": "التسعير لكل فرع",
  pricing: "الأسعار",
  "pricing-rules-by-slot-member-type-and": "قواعد تسعير حسب الموعد ونوع العضوية والموسم",
  priority: "أولوية",
  "priority-onboarding": "تهيئة ذات أولوية",
  "priority-onboarding-and-support": "تهيئة ودعم بأولوية",
  "privacy-policy-terms-of-service-and-data":
    "سياسة الخصوصية وشروط الخدمة ووثائق معالجة البيانات لم تُنشر على هذا الموقع بعد — تُصدر ضمن التهيئة. اطلبها في أي وقت قبل التوقيع.",
  "product-evidence": "دليل من المنتج",
  "product-experience": "تجربة المنتج",
  "product-resources": "مصادر المنتج",
  "product-updates": "تحديثات المنتج",
  "product-vision": "رؤية المنتج",
  "profiles-guardians-and-emergency-contacts-on-one": "الملفات وأولياء الأمور وجهات الطوارئ في سجل واحد",
  "profiles-guardians-documents-and-history-that-surviv":
    "ملفات وأولياء أمور ومستندات وسجل يبقى رغم تغيّر الفريق أو الفرع أو الموسم.",
  "programme-progression-marked-evidence": "تقدّم البرنامج · أدلة مُسجَّلة",
  programs: "البرامج",
  "programs-athletes-guardians-coaches-attendance-subsc":
    "البرامج واللاعبون وأولياء الأمور والمدربون والحضور والاشتراكات والمدفوعات في إيقاع واحد — لتبقى أدلة التطوير بعد الموسم الذي جُمعت فيه.",
  "programs-groups-and-sessions": "البرامج والمجموعات والحصص",
  "programs-groups-and-sessions-structured-by-stage": "برامج ومجموعات وحصص مبنية على المرحلة، لا مرتجلة كل فصل.",
  "programs-groups-and-sessions-with-attendance-subscri":
    "برامج ومجموعات وحصص مرتبط بها الحضور والاشتراكات والتواصل مع أولياء الأمور.",
  "programs-surfaces-and-bookings-are-sport-agnostic":
    "البرامج والملاعب والحجوزات لا ترتبط برياضة بعينها. البادل والسباحة وكرة السلة والتنس والجمباز تعمل بجانب كرة القدم على الشبكة نفسها.",
  "programs-surfaces-and-bookings-are-sport-agnostic-5601":
    "البرامج والملاعب والحجوزات لا ترتبط برياضة بعينها. إضافة البادل أو السباحة أو كرة السلة بجانب كرة القدم لا تغيّر الخطة.",
  "programs-surfaces-and-bookings-are-sport-agnostic-7205":
    "البرامج والملاعب والحجوزات لا ترتبط برياضة بعينها — البادل والسباحة وكرة السلة والتنس والجمباز تعمل بجانب كرة القدم.",
  "programs-surfaces-and-bookings-are-sport-agnostic-b4b1":
    "البرامج والملاعب والحجوزات لا ترتبط برياضة بعينها: البادل والسباحة وكرة السلة والتنس والجمباز بجانب كرة القدم.",
  "public-swim-90-min": "سباحة عامة · ٩٠ دقيقة",
  "published-as-they-are-written": "تُنشر فور كتابتها.",
  "put-every-court-field-and-pool-on":
    "ضع كل ملعب وميدان ومسبح على شبكة واحدة — وسترى ساعات الذروة التي تبيعها يدويًا اليوم.",
  questions: "الأسئلة",
  "quoted-on-branches-sports-and-volume": "يُسعَّر على أساس الفروع والرياضات والحجم",
  "r-sabri": "ر. صبري",
  "rana-sabri": "رنا صبري",
  "ready-to-run-your-sports-organization-differently": "مستعد لإدارة منظمتك الرياضية بشكل مختلف؟",
  "recent-payments": "أحدث المدفوعات",
  reception: "الاستقبال",
  "reception-finance-and-the-technical-staff-working":
    "الاستقبال والمالية والجهاز الفني يعملون على اليوم نفسه، لا على ثلاثة ملفات تصدير.",
  "reception-maintenance-and-finance-reading-one-grid":
    "الاستقبال والصيانة والمالية يقرأون شبكة واحدة بدل التفاوض عبر الهاتف.",
  reconciled: "مُطابَق",
  "reconciled-and-reportable-the-same-day": "مُطابَق وقابل للتقرير في اليوم نفسه.",
  "reconciled-the-same-day-reportable-the-same": "مُطابَق في اليوم نفسه، وقابل للتقرير في اليوم نفسه",
  "reconciled-the-same-day-the-sessions-happened": "مُطابَق في اليوم نفسه الذي جرت فيه الحصص",
  "recurring-block-week-4-of-8": "بلوك متكرر · الأسبوع ٤ من ٨",
  "recurring-blocks-that-survive-a-fixture-clash": "بلوكات متكررة تصمد أمام تعارض المباريات",
  "recurring-booking-8-weeks": "حجز متكرر · ٨ أسابيع",
  "release-1-sends-updates-a-guardian-portal": "الإصدار الأول يرسل التحديثات. وبوابة أولياء الأمور ضمن خارطة الطريق.",
  "reminders-sent-before-kick-off-not-after": "التذكيرات تُرسل قبل صافرة البداية، لا بعدها",
  "renewal-and-payment-notices-on-the-plan": "إشعارات التجديد والدفع وفق جدول الخطة نفسها",
  "renewal-windows-pauses-and-pro-rata-handled": "نوافذ التجديد والإيقاف والحساب النسبي مُدارة داخل الخطة",
  renewing: "قيد التجديد",
  reporting: "التقارير",
  "reporting-built-from-the-record-not-re": "تقارير مبنية من السجل، لا معادة الإدخال",
  reports: "التقارير",
  "reservation-confirmed": "تأكيد الحجز",
  reservations: "الحجوزات",
  "reservations-and-pricing-rules": "الحجوزات وقواعد التسعير",
  resources: "المصادر",
  response: "الرد",
  "results-and-availability-feed-the-next-selection": "النتائج والجاهزية تغذّي الانتقاء التالي",
  "resume-dates-set": "تحديد تواريخ الاستئناف",
  revenue: "الإيرادات",
  "revenue-members-reservations-attendance-events-and-p":
    "الإيرادات والأعضاء والحجوزات والحضور والفعاليات والمدفوعات — مُطابَقة على السجل نفسه، في اليوم نفسه.",
  "revenue-members-reservations-attendance-events-payme":
    "الإيرادات والأعضاء والحجوزات والحضور والفعاليات والمدفوعات والرؤى — تُقرأ معًا وتُطابَق في اليوم نفسه.",
  "revenue-membership-attendance-and-utilization-in-one": "الإيرادات والعضوية والحضور ومعدل الاستخدام في عرض واحد",
  "revenue-this-month": "إيرادات هذا الشهر",
  "roles-and-permissions-scoped-per-branch": "أدوار وصلاحيات محددة لكل فرع",
  "roles-scoped-per-branch-and-per-module":
    "أدوار محددة لكل فرع ولكل وحدة، ليرى كل شخص التشغيل المسؤول عنه.",
  "rolling-out-the-coach-app": "إطلاق تطبيق المدرب",
  "roster-and-session-plan-on-the-phone": "القائمة وخطة الحصة على الهاتف.",
  "rosters-session-plans-cover-and-load-for":
    "القوائم وخطط الحصص والبدلاء والحمل — لمن يديرون الحصص فعلًا.",
  "rosters-session-plans-cover-requests-and-weekly":
    "القوائم وخطط الحصص وطلبات البدلاء والحمل الأسبوعي — لمن يديرون الحصص.",
  "run-the-club-not-the-spreadsheet": "أدِر النادي، لا جدول البيانات.",
  "run-the-entire-operation-from-one-dashboard": "أدِر التشغيل بالكامل من لوحة واحدة.",
  "s-meligy": "س. المليجي",
  "sales-assisted-always": "بمرافقة فريق المبيعات، دائمًا",
  "sales-assisted-from-first-call-to-first": "بمرافقة فريق المبيعات، من أول مكالمة إلى أول موسم.",
  "sales-assisted-onboarding-no-self-service-provisioni": "تهيئة بمرافقة فريق المبيعات، دون تفعيل ذاتي.",
  "sales-assisted-onboarding-typically-live-within-one":
    "تهيئة بمرافقة فريق المبيعات · التشغيل عادةً خلال فترة توقف موسم واحدة.",
  "same-cycle-rate": "معدل الدورة نفسها",
  "same-day-close": "إغلاق في اليوم نفسه",
  "same-day-close-rate": "معدل الإغلاق في اليوم نفسه",
  "same-day-close-rate-is-a-number": "معدل الإغلاق في اليوم نفسه رقم، لا تخمين",
  "same-definitions-across-every-module-reconciled-the":
    "التعريفات نفسها عبر كل وحدة، مُطابَقة في اليوم نفسه الذي جرت فيه الحصص.",
  "same-platform-different-centre-of-gravity": "المنصة نفسها. مركز ثقل مختلف.",
  "sample-data": "بيانات تجريبية",
  "sample-data-indicative-of-a-mid-size": "بيانات تجريبية — تمثّل منظمة متوسطة الحجم.",
  "sample-data-replaced-with-yours-during-onboarding": "بيانات تجريبية — تُستبدل ببياناتك أثناء التهيئة.",
  "sar-214k": "‏٢١٤ ألف ريال",
  "sar-bookings-memberships": "ريال · حجوزات + عضويات",
  sat: "السبت",
  "sat-09-00-alexandria": "السبت ٠٩:٠٠ · الإسكندرية",
  "sat-14-00-olympic-pool": "السبت ١٤:٠٠ · المسبح الأولمبي",
  saturday: "السبت",
  "scripe-brings-memberships-reservations-payments-coac":
    "يجمع SCRIPE العضويات والحجوزات والمدفوعات والتدريب والمسابقات والتواصل وذكاء الأعمال في منصة واحدة متصلة.",
  "scripe-exists-for-the-part-of-sport":
    "وُجد SCRIPE للجزء الذي لا يصوّره أحد في الرياضة — الجدول، وطلب البديل، ودفعة الفصل، وكشف الحضور.",
  "scroll-to-fly-over": "مرّر للتحليق فوق المكان",
  search: "بحث",
  "season-over-season-comparison-on-one-definition": "مقارنة موسم بموسم على تعريف واحد",
  "see-all-13-capabilities-on-the-platform": "شاهد القدرات الـ١٣ في صفحة المنصة",
  "see-how-the-dashboard-is-assembled": "شاهد كيف تُبنى لوحة التشغيل",
  "see-pricing": "اطّلع على الأسعار",
  "see-the-automation-and-notification-modules": "شاهد وحدتَي الأتمتة والإشعارات",
  "see-the-platform-against-your-own-operation": "شاهد المنصة على تشغيلك أنت.",
  "select-one": "اختر واحدًا",
  "sent-18-04": "أُرسل ١٨:٠٤",
  "sent-before-kick-off-not-after-it": "يُرسل قبل صافرة البداية، لا بعدها.",
  "session-and-attendance-updates-sent-automatically": "تحديثات الحصص والحضور تُرسل تلقائيًا",
  "session-confirmed-u14-technical-block": "تأكيد الحصة · بلوك فني تحت ١٤",
  "session-plans-and-rosters-on-the-coach": "خطط الحصص والقوائم على هاتف المدرب",
  "session-plans-and-rosters-on-the-phone":
    "خطط الحصص والقوائم على الهاتف؛ والملاحظات تصل إلى الانتقاء دون إعادة كتابة.",
  "sessions-per-week": "حصص أسبوعيًا",
  "sessions-surfaces-and-staff-held-together-in": "الحصص والملاعب والطاقم تُحجز معًا في خطوة واحدة",
  "sessions-surfaces-staff-and-payments-held-together":
    "الحصص والملاعب والطاقم والمدفوعات مترابطة، فيجيب الجدول عن الأسئلة بدل أن يثيرها.",
  "setting-pricing-rules-for-surfaces": "ضبط قواعد التسعير للملاعب",
  "setup-guides-the-questions-operations-leaders-actual":
    "أدلة إعداد، والأسئلة التي يطرحها مسؤولو التشغيل فعلًا، ومرجع لكل وحدة في المنصة.",
  "short-pieces-on-operations-written-as-they":
    "مقالات قصيرة عن التشغيل، تُكتب وقت حدوثه. تُنشر عند الإطلاق.",
  "small-sided-u14": "ملاعب مصغّرة · تحت ١٤",
  solutions: "الحلول",
  "specialist-coach-management": "إدارة متخصصة للمدربين",
  sports: "الرياضات",
  "sports-academies": "الأكاديميات الرياضية",
  "sports-academies-0af5": "الأكاديميات الرياضية",
  "sports-clubs": "الأندية الرياضية",
  "sports-clubs-a004": "الأندية الرياضية",
  "sports-do-not-cost-extra": "الرياضات لا تكلّف إضافيًا",
  "sports-operations": "التشغيل الرياضي",
  "sports-venues": "المنشآت الرياضية",
  "sports-venues-a9af": "المنشآت الرياضية",
  "squad-availability-this-week": "جاهزية الفريق · هذا الأسبوع",
  "squad-selection-from-the-same-member-record": "انتقاء الفريق من سجل العضو نفسه",
  "squad-set": "تحديد الفريق",
  squads: "الفرق",
  "squads-by-age-group-and-sport-selected":
    "فرق حسب الفئة العمرية والرياضة، تُنتقى من سجل العضو نفسه الذي يقرأه بقية النادي.",
  "squads-groups-and-programs-without-duplicate-entries": "فرق ومجموعات وبرامج دون إدخالات مكررة",
  "squads-membership-the-competition-calendar-attendanc":
    "الفرق والعضوية وروزنامة المسابقات والحضور والمدفوعات في سجل واحد متصل.",
  standard: "قياسي",
  "standard-reports": "تقارير قياسية",
  "start-free-trial": "ابدأ نسخة تجريبية",
  "start-where-your-organization-actually-sits": "ابدأ من حيث تقف منظمتك فعلًا.",
  starter: "البداية",
  "starter-and-growth-are-quoted-per-branch":
    "تُسعَّر خطتا البداية والنمو لكل فرع. وتُضاف الفروع الإضافية إلى المنظمة نفسها، لا كنظام ثانٍ.",
  subscriptions: "الاشتراكات",
  "subscriptions-and-renewals": "الاشتراكات والتجديدات",
  "subscriptions-match-fees-and-outstanding-balances-at":
    "الاشتراكات ورسوم المباريات والأرصدة المستحقة مرتبطة بالحصة التي ولّدتها.",
  "subscriptions-this-week": "الاشتراكات · هذا الأسبوع",
  sun: "الأحد",
  "sun-19-00-courts-1-3": "الأحد ١٩:٠٠ · الملاعب ١–٣",
  support: "الدعم",
  "surface-by-surface-utilization-so-unsold-capacity":
    "معدل استخدام لكل ملعب على حدة، لتظهر الطاقة غير المباعة وهي ما تزال قابلة للبيع.",
  "surface-coach-and-time-held-at-once": "الملعب والمدرب والوقت تُحجز معًا دفعة واحدة.",
  surfaces: "الملاعب",
  "surfaces-coaches-and-time-held-together-in": "الملاعب والمدربون والوقت تُحجز معًا في خطوة واحدة",
  "surfaces-tuesday-evening": "الملاعب · مساء الثلاثاء",
  "swim-squad-lanes-3-5": "فريق السباحة · الحارات ٣–٥",
  "swim-squad-monthly": "فريق السباحة · شهري",
  "swim-time-trials": "اختبارات زمن السباحة",
  swimming: "السباحة",
  "swimming-academies": "أكاديميات السباحة",
  "swimming-squad": "فريق السباحة",
  "t-aziz": "ت. عزيز",
  "talk-to-sales": "تحدث إلى المبيعات",
  "talk-to-the-people-building-it": "تحدث إلى من يبنونه.",
  "teams-and-squads": "الفرق والتشكيلات",
  "teams-members-and-the-competition-calendar": "الفرق والأعضاء وروزنامة المسابقات",
  "teams-members-competitions-and-club-operations-from": "الفرق والأعضاء والمسابقات وتشغيل النادي من مكان واحد.",
  "teams-members-the-competition-calendar-attendance-pa":
    "الفرق والأعضاء وروزنامة المسابقات والحضور والمدفوعات والمدربون في سجل واحد متصل — ليكون سؤال الخامسة مساءً مُجابًا قبل أن يسأله أحد.",
  "technical-u12-u14": "فني · تحت ١٢–١٤",
  "technology-that-stays-out-of-the-way": "تقنية لا تقف في الطريق",
  "tell-us-how-the-organization-is-set":
    "أخبرنا كيف تُدار منظمتك وسنربط برامجك وملاعبك وطاقمك قبل المكالمة.",
  "term-and-monthly-plans-that-renew-on":
    "خطط فصلية وشهرية تتجدد وفق القاعدة التي تضعها، مع معالجة تسعير الإخوة.",
  "term-monthly-and-recurring-plans-side-by": "خطط فصلية وشهرية ومتكررة جنبًا إلى جنب",
  "term-payment-due-in-5-days": "دفعة الفصل مستحقة خلال ٥ أيام",
  "terms-monthly-plans-and-recurring-blocks-that":
    "فصول وخطط شهرية وبلوكات متكررة تتجدد وفق القاعدة التي تضعها، لا وفق تذكّر أحدهم.",
  "the-coach-app-holds-session-plans-rosters":
    "يحتوي تطبيق المدرب على خطط الحصص والقوائم والحضور والملاحظات، ويعمل دون إنترنت عند انقطاع التغطية في الملعب.",
  "the-modules-that-match-your-operation-in": "الوحدات التي تناسب تشغيلك، على جدولك أنت",
  "the-operating-day": "يوم التشغيل",
  "the-operating-picture-your-board-asks-for":
    "الصورة التشغيلية التي يطلبها مجلس إدارتك، مبنية من السجل بدل إعادة إدخالها في عرض تقديمي.",
  "the-operating-system-for-modern-sports-organizations": "نظام تشغيل المنظمات الرياضية الحديثة",
  "the-operational-partner-behind-modern-sports-organiz": "الشريك التشغيلي خلف المنظمات الرياضية الحديثة.",
  "the-organization-is-told-what-changed-while": "تُبلَّغ المنظمة بما تغيّر بينما لا يزال هناك وقت للتصرف.",
  "the-page-may-have-moved-the-platform":
    "ربما انتقلت الصفحة. المنصة والحلول الأربعة والأسعار والمصادر جميعها على بُعد نقرة واحدة.",
  "the-record-underneath-is-the-same-in": "السجل تحتها هو نفسه في الأربعة جميعًا.",
  "the-record-underneath-stays-the-same-whichever": "السجل تحتها يبقى نفسه أيًا كانت الوحدات التي تشغّلها.",
  "the-work-that-decides-everything-happens-between":
    "العمل الذي يحسم كل شيء يجري بين الحصص: من يغطي الملعب الثاني، وأي حارة متاحة، وهل دُفع الفصل. صُمم SCRIPE حول هذا العمل، لا حول لوحة عرض.",
  "there-is-no-self-service-provisioning-programs":
    "لا يوجد تفعيل ذاتي. تُربط البرامج والملاعب والطاقم مع فريقك قبل أي إطلاق — وتُغطّى الخصوصية والشروط ومعالجة البيانات في المحادثة نفسها.",
  "there-is-no-self-service-provisioning-trials":
    "لا يوجد تفعيل ذاتي. تُحدَّد النسخ التجريبية والخطط مع فريقنا لتُربط برامجك وملاعبك وطاقمك أولًا.",
  "thirteen-capabilities-on-one-connected-record-switch":
    "ثلاث عشرة قدرة على سجل واحد متصل. فعّل الوحدات كلما نمت المنظمة — دون إعادة إدخال أو إعادة كتابة أو مطابقة مرتين.",
  "thirteen-capabilities-what-each-one-does-and":
    "ثلاث عشرة قدرة، وما تفعله كل واحدة، وما الذي تحل محله. كل منها يربط مباشرة بصفحة المنصة.",
  "this-is-the-part-nobody-sees-and": "هذا هو الجزء الذي لا يراه أحد — وهو الجزء الذي يحسم كل شيء.",
  "this-route-does-not-exist": "هذا المسار غير موجود.",
  "this-week": "هذا الأسبوع",
  "three-plans-billed-monthly-or-yearly-every":
    "ثلاث خطط، تُفوتر شهريًا أو سنويًا. كل خطة تُؤكَّد مع فريق التشغيل لديك قبل التوقيع — والأرقام أدناه استرشادية.",
  "three-things-worth-knowing-before-the-call": "ثلاثة أمور تستحق المعرفة قبل المكالمة.",
  thu: "الخميس",
  thursday: "الخميس",
  "today-s-reservations": "حجوزات اليوم",
  "today-tuesday": "اليوم · الثلاثاء",
  "total-members": "إجمالي الأعضاء",
  trial: "اختبار",
  "trial-period-2-sessions-left": "فترة تجريبية · تبقّت حصتان",
  "trial-sessions-booked-straight-onto-the-real": "حصص الاختبار تُحجز مباشرة على الشبكة الحقيقية",
  "trials-and-selection": "الاختبارات والانتقاء",
  "trials-are-set-up-with-our-team":
    "تُعدّ النسخ التجريبية مع فريقنا لتُربط برامجك وملاعبك وطاقمك قبل أن تجربها. اطلب واحدة وسنحددها معك.",
  "trials-booked": "اختبارات محجوزة",
  "trusted-by-modern-sports-organizations": "موضع ثقة المنظمات الرياضية الحديثة",
  tue: "الثلاثاء",
  "tuesday-16-30-pitch-2": "الثلاثاء ١٦:٣٠ · الملعب ٢",
  "tuesday-4-52pm-three-pitches-five-groups":
    "الثلاثاء، ٤:٥٢ مساءً. ثلاثة ملاعب، خمس مجموعات، مدربان غائبان، وولي أمر على الهاتف. هذا هو الجزء الذي لا يراه أحد — وهو الجزء الذي يحسم كل شيء. يربطه SCRIPE في نظام واحد ليكون الجواب حاضرًا قبل أن يصل السؤال.",
  "turn-operations-into-decisions": "حوّل التشغيل إلى قرارات.",
  "two-of-five-evening-slots-on-pitch": "يبقى موعدان من خمسة مواعيد مسائية في الملعب ٢ دون بيع.",
  "u12-technical-block": "تحت ١٢ · بلوك فني",
  "u14-small-sided": "تحت ١٤ · ملاعب مصغّرة",
  "u16-league-away": "دوري تحت ١٦ · خارج الأرض",
  "u16-position-trials": "تحت ١٦ · اختبارات المراكز",
  "u8-foundation": "تحت ٨ · التأسيس",
  unlimited: "غير محدود",
  "unsold-capacity-surfaced-while-it-can-still": "الطاقة غير المباعة تظهر وهي ما تزال قابلة للبيع",
  "upcoming-events": "الفعاليات القادمة",
  "use-the-form-it-reaches-the-same": "استخدم النموذج — فهو يصل إلى الفريق نفسه.",
  utilization: "معدل الاستخدام",
  "utilization-across-7-sports-and-17-surfaces": "معدل الاستخدام عبر ٧ رياضات و١٧ ملعبًا، على خط تقارير واحد.",
  "utilization-by-branch": "معدل الاستخدام حسب الفرع",
  "utilization-by-surface": "معدل الاستخدام حسب الملعب",
  "venue-led": "بقيادة المنشأة",
  "venue-operations": "تشغيل المنشأة",
  "venue-utilization": "معدل استخدام المنشأة",
  venues: "المنشآت",
  "we-build-for-owners-directors-and-operations":
    "نبني للملّاك والمديرين ومسؤولي التشغيل، ومعهم المدربون وموظفو الاستقبال الذين يعيشون داخل المنتج كل يوم. وكل وحدة تستحق مكانها بإلغاء خطوة يقوم بها أحدهم يدويًا اليوم.",
  "we-map-your-programs-surfaces-and-staff":
    "نربط برامجك وملاعبك وطاقمك قبل أن تجربه — ليكون العرض على جدولك أنت، لا على جدولنا.",
  "we-map-your-squads-fixtures-and-coaching":
    "نربط فرقك ومبارياتك وجهازك الفني قبل العرض، لترى أسبوع مبارياتك أنت يعمل على SCRIPE.",
  wed: "الأربعاء",
  wednesday: "الأربعاء",
  "weekly-load-visible-per-coach-not-per": "الحمل الأسبوعي ظاهر لكل مدرب، لا بالتخمين",
  "what-a-guardian-receives": "ما الذي يصل إلى ولي الأمر",
  "what-each-plan-actually-includes": "ما تشمله كل خطة فعلًا.",
  "what-happens-next": "ما الذي يحدث بعد ذلك",
  "what-is-actually-free-right-now-not": "ما المتاح فعلًا الآن — لا ما قاله المخطط الجداري هذا الصباح.",
  "what-is-scripe": "ما هو SCRIPE؟",
  "what-kind-of-organization": "ما نوع المنظمة؟",
  "what-multi-sports-organizations-actually-run-on": "ما الذي تعمل عليه المنظمات متعددة الرياضات فعلًا.",
  "what-never-changes": "ما لا يتغير",
  "what-shipped-what-changed-and-what-it": "ما أُطلق، وما تغيّر، وما الذي يحل محله. يُنشر عند الإطلاق.",
  "what-sports-academies-actually-run-on": "ما الذي تعمل عليه الأكاديميات الرياضية فعلًا.",
  "what-sports-clubs-actually-run-on": "ما الذي تعمل عليه الأندية الرياضية فعلًا.",
  "what-sports-venues-actually-run-on": "ما الذي تعمل عليه المنشآت الرياضية فعلًا.",
  "what-the-first-four-weeks-with-an": "كيف تبدو الأسابيع الأربعة الأولى مع فريق تشغيل.",
  "what-this-looks-like": "كيف يبدو ذلك",
  "what-to-migrate-what-to-leave-behind": "ما يُنقل، وما يُترك، وكيف يُحمل سجل الحضور معه.",
  "where-demand-actually-sits-by-hour-and":
    "أين يقع الطلب فعلًا بحسب الساعة والرياضة، مُتتبَّعًا وهو يتحرك عبر الموسم.",
  "who-is-scripe-for": "لمن SCRIPE؟",
  "with-your-operations-team": "مع فريق التشغيل لديك",
  "within-one-working-day": "خلال يوم عمل واحد",
  "working-with-us": "العمل معنا",
  "works-offline-and-syncs-when-signal-returns": "يعمل دون إنترنت ويُزامن عند عودة التغطية",
  "written-with-the-operations-teams-doing-it":
    "مكتوبة مع فرق التشغيل التي تقوم بها. تُنشر كل واحدة فور اكتمالها — لا شيء هنا حشو.",
  yearly: "سنويًا",
  "yes-each-branch-runs-its-own-timetable":
    "نعم. كل فرع يدير جدوله وطاقمه، بينما تقرأ تقارير المجموعة عبرها جميعًا دون سجلات مكررة.",
  "yes-one-off-and-recurring-bookings-pricing":
    "نعم. الحجوزات المفردة والمتكررة وقواعد التسعير والدفع وتسجيل الدخول على الشبكة نفسها، ومُطابَقة في اليوم نفسه.",
  "you-organization-com": "you@organization.com",
  "your-operations-should-run-themselves": "يجب أن يدير تشغيلك نفسه بنفسه.",
  "your-programs-surfaces-and-staff-mapped-before": "برامجك وملاعبك وطاقمك مربوطة قبل العرض",
  "yusuf-adel-u16": "يوسف عادل · تحت ١٦",
};
