/**
 * Web app manifest (`manifest.webmanifest`).
 *
 * Minimal PWA metadata — SCRIPE's public site is not an installable app
 * today, but a manifest still improves the "Add to Home Screen"/mobile tab
 * presentation and is a standard SEO/PWA-readiness check.
 *
 * Task E6 (3D Brand System Everywhere): the icons below are real rasterized
 * PNGs — `public/brand/icons/icon-{192,512}.png`, generated by
 * `scripts/build-brand-assets.mjs` from the owner's
 * `SCRIPE_3D_APP_ICON_GLOSSY.png` original (the finished dark-tile+glow app
 * icon composition, not the bare mark) — replacing the placeholder-era SVG
 * entry this file used to carry before those PNGs existed.
 */
import type { MetadataRoute } from "next";

/**
 * Builds the site's web app manifest.
 *
 * @returns Manifest fields: name/description, obsidian theme + background
 *   color (matches `<meta name="theme-color">` in
 *   `src/app/[locale]/layout.tsx`), standalone display, and the 192/512
 *   PWA icon pair.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "SCRIPE",
    short_name: "SCRIPE",
    description: "The Operating System for Modern Sports Organizations.",
    start_url: "/",
    display: "standalone",
    theme_color: "#0B0B0E",
    background_color: "#0B0B0E",
    icons: [
      {
        src: "/brand/icons/icon-192.png",
        type: "image/png",
        sizes: "192x192",
        purpose: "any",
      },
      {
        src: "/brand/icons/icon-512.png",
        type: "image/png",
        sizes: "512x512",
        purpose: "any",
      },
    ],
  };
}
