/**
 * Locale-aware OpenGraph image for the `[locale]` route subtree.
 *
 * One image per locale (`en`/`ar`), generated at build time via
 * `generateStaticParams` below (the `[locale]` segment is already fully
 * static — `dynamicParams = false` in `src/app/[locale]/layout.tsx` — this
 * file mirrors that so both locale images prerender rather than falling
 * back to per-request generation). This is a site-wide image, not a
 * per-page one: individual page tasks may add their own nested
 * `opengraph-image.tsx` later if a page needs a bespoke image, but none do
 * yet, so every page under a locale shares this file's output.
 *
 * Font note (Task G5 — real brand typography): Satori (the renderer behind
 * `next/og`'s `ImageResponse`) can only parse TrueType/OpenType-container
 * fonts (magic bytes `\x00\x01\x00\x00`, `"OTTO"`, or `"true"`) — never
 * WOFF/WOFF2. Every font asset this project ships for the live site
 * (`src/fonts/*.woff2`) is a variable WOFF2, unparseable by Satori (verified
 * locally against next@16.3.1's bundled `@vercel/og`: handing the raw
 * `Archivo-var.woff2` buffer to `ImageResponse` throws `Unsupported OpenType
 * signature wOF2`). That's why this card used to render in Satori's
 * fallback font instead of Archivo.
 *
 * The fix: `scripts/build-og-fonts.py` mechanically derives STATIC
 * (non-variable) `.ttf` instances from the same owned `Archivo-var.woff2` —
 * `fontTools.varLib.instancer` pins the `wght`/`wdth` axes to the two
 * weights this card actually uses (800 for the wordmark, 400 for the
 * tagline), then `fontTools.subset` cuts each to the project's existing
 * Latin block policy (same ranges `scripts/subset-fonts.mjs` uses). Output
 * lands in `src/fonts/og/*.ttf` — build-time-only assets this route reads
 * from disk, never shipped to the browser (unlike `src/fonts/*.woff2`,
 * nothing under `src/fonts/og/` is ever passed to `next/font/local`). Both
 * instances are still signature-checked below before use — not because
 * they're expected to fail (`build-og-fonts.py`'s only job is producing a
 * parseable SFNT), but so a bad re-run or an accidentally-reintroduced
 * WOFF2 fails loud (fallback font) instead of crashing the build.
 *
 * A second, unrelated Satori quirk to preserve if this file is edited: a
 * style object's `fontFamily` key must be entirely absent when there is no
 * custom font, not present with value `undefined` — Satori's font-family
 * parser unconditionally calls `.split(",")` on it, so an explicit
 * `fontFamily: undefined` throws `Cannot read properties of undefined
 * (reading 'split')` at prerender time (reproduced locally; only surfaces
 * under `next build`, not in ad-hoc `ImageResponse` calls outside the
 * framework). That is why {@link fontFamilyStyle} conditionally spreads the
 * key in rather than assigning it a possibly-`undefined` value directly.
 *
 * Task E6 (3D Brand System Everywhere): the flat lime accent bar this card
 * used to draw is now the owner's real 3D mark. `ImageResponse`/Satori can't
 * read an arbitrary file path as an image element's `src` attribute — the
 * sanctioned pattern (per Vercel's `next/og` docs) is a base64 data URI, so
 * {@link loadMarkDataUri} reads the small pre-shrunk derivative
 * (`public/brand/mark/scripe-mark-og.png`, 220×174, ~49KB — generated by
 * `scripts/build-brand-assets.mjs` from the owner's
 * `SCRIPE_3D_MARK_TRANSPARENT.png` original) and inlines it once per
 * render. That derivative, not the 1.4MB source, is what keeps the
 * generated 1200×630 PNG comfortably under the 500KB OG-image budget.
 */
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { ImageResponse } from "next/og";
import { routing } from "@/i18n/routing";

/** Alt text for the generated image. */
export const alt = "SCRIPE — Sports Operations OS";
/** Pixel dimensions Next.js renders this route at and links in `<meta>` tags. */
export const size = { width: 1200, height: 630 };
/** MIME type of the generated image. */
export const contentType = "image/png";

const OBSIDIAN = "#0B0B0E";
const SIGNAL_LIME = "#C0FF00";
const NEAR_WHITE = "#F4F6F0";

/** Per-locale OG image copy. */
interface OgLocaleContent {
  /** Tagline rendered under the "SCRIPE" wordmark. */
  tagline: string;
  /** Whether the layout mirrors for a right-to-left reading locale. */
  isRtl: boolean;
}

/**
 * Per-locale content for the OG image.
 *
 * The `ar` entry deliberately does NOT contain the real Arabic tagline
 * (`messages/ar.json`'s `footer.tagline`, "نظام تشغيل المنظمات الرياضية
 * الحديثة"). Task 12 first found that `ImageResponse` cannot shape
 * Arabic-script text at all in next@16.3.1: it throws `lookupType: 5 -
 * substFormat: 3 is not yet supported` from Satori's bundled Arabic-shaping
 * code, reproduced even with Satori's own default font (not a font-loading
 * problem). Task 12 left open whether a STATIC (non-variable) Arabic font
 * might avoid it, since the only Arabic assets tried then were variable and
 * separately crashed Satori's `fvar` parser for an unrelated reason.
 *
 * Task G5 closed that question: it does not. Two static instances were
 * derived with the same `fontTools.varLib.instancer` pipeline that fixed
 * the Latin/Archivo case above — Noto Sans Arabic Regular (400) and Noto
 * Kufi Arabic SemiBold (600), both pinned from the variable `.woff2`s this
 * project already owns (`src/fonts/NotoSansArabic-var.woff2`,
 * `NotoKufiArabic-var.woff2`) via `scripts/build-og-fonts.py`. Both are
 * valid, Satori-parseable SFNT TTFs (confirmed: correct `\x00\x01\x00\x00`
 * signature, load without error). Both still crash the instant Arabic text
 * is shaped through them — identical error, identical call stack, for
 * *both* faces:
 *
 *   Error: lookupType: 5 - substFormat: 3 is not yet supported
 *       at FeatureQuery.getLookupMethod (.../@vercel/og/index.node.js:10032)
 *       at FeatureQuery.lookupFeature (.../@vercel/og/index.node.js:10057)
 *       at Bidi.arabicRequiredLigatures (.../@vercel/og/index.node.js:10358)
 *       at Bidi.applyArabicRequireLigatures (.../@vercel/og/index.node.js:10527)
 *       at Bidi.applyFeaturesToContexts (.../@vercel/og/index.node.js:10553)
 *       at Bidi.processText (.../@vercel/og/index.node.js:10566)
 *
 * Reproduced deterministically (5/5 runs, both the full `footer.tagline`
 * string and short 1–2 word fragments) against a standalone
 * `next/og`/`ImageResponse` call outside the Next build — this is Satori's
 * own bundled OpenType-shaping engine failing to implement GSUB lookup type
 * 5 / substFormat 3 (a coverage-based chained contextual substitution,
 * which real Arabic fonts' `ArabicRequiredLigatures` GSUB feature needs for
 * baseline shaping). It fires inside `Bidi.arabicRequiredLigatures` before
 * any per-font lookup succeeds or fails on its own merits, so it is NOT
 * avoidable by font choice, weight, or variable-vs-static — confirmed
 * across two different Arabic typefaces here, on top of Task 12's default-
 * font reproduction. There is no known way to render literal Arabic-script
 * text through this Next.js/`@vercel/og` version at all.
 *
 * Given "do NOT ship a broken image route," the `ar` image keeps Task 12's
 * mitigation: a mirrored RTL layout (mark and text align right) with the
 * English-language tagline text, not a translated one. Flagged for Task 26
 * visual QA, same as before.
 *
 * TODO(task-12, reconfirmed task-g5): once `@vercel/og`/Satori ships GSUB
 * lookup type 5 support (or this route moves off `next/og`), swap this back
 * to the real Arabic tagline and delete this comment. The derived Arabic
 * fonts that were proven to load correctly (just not to shape) are not
 * committed under `src/fonts/og/` — only the two Archivo weights that are
 * actually used are — but `scripts/build-og-fonts.py` documents exactly how
 * to regenerate them the moment this is worth revisiting.
 */
const CONTENT: Record<"en" | "ar", OgLocaleContent> = {
  en: { tagline: "Sports Operations OS", isRtl: false },
  ar: { tagline: "Sports Operations OS", isRtl: true },
};

/** Directory holding this route's build-time-only static font instances
 *  (never shipped to the browser — see the file header). */
const OG_FONTS_DIR = join(process.cwd(), "src/fonts/og");

/**
 * Loads one static Archivo weight for Satori from `src/fonts/og/`.
 *
 * @param filename - e.g. `"Archivo-ExtraBold.ttf"` — see
 *   `scripts/build-og-fonts.py` for how these are derived.
 * @returns The font's raw bytes when its magic bytes match a
 *   TrueType/OpenType container, otherwise `null`. Callers must omit the
 *   corresponding `fonts` entry when this returns `null` — Satori's bundled
 *   default font still renders Latin text correctly without it.
 */
async function loadArchivoWeight(filename: string): Promise<Buffer | null> {
  try {
    const buffer = await readFile(join(OG_FONTS_DIR, filename));
    const signature = buffer.subarray(0, 4).toString("ascii");
    const isTrueTypeSfnt = buffer.length >= 4 && buffer.readUInt32BE(0) === 0x00010000;
    if (signature === "OTTO" || signature === "true" || isTrueTypeSfnt) {
      return buffer;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Loads the small OG-card mark derivative and returns it as a base64 data
 * URI — the only way `ImageResponse`/Satori can resolve a local file as an
 * image element's `src`. See the file header for why this reads the
 * pre-shrunk 220×174 derivative rather than a source original.
 *
 * @returns A `data:image/png;base64,...` URI. Unlike {@link loadArchivoWeight}
 *   this has no failure/fallback mode — the derivative is a build-script
 *   output checked into `public/`, not an optional enhancement.
 */
async function loadMarkDataUri(): Promise<string> {
  const buffer = await readFile(join(process.cwd(), "public/brand/mark/scripe-mark-og.png"));
  return `data:image/png;base64,${buffer.toString("base64")}`;
}

/** Prerenders both locale images at build time, matching the parent layout. */
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

/**
 * Renders the OG image for one locale: obsidian ground, the real SCRIPE
 * mark, and the "SCRIPE" wordmark with its tagline underneath. The `ar`
 * layout mirrors (mark and text align to the right) without containing
 * literal Arabic glyphs — see {@link CONTENT}'s doc comment.
 *
 * @param props.params - Resolves to the matched `[locale]` segment.
 */
export default async function Image({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const content = locale === "ar" ? CONTENT.ar : CONTENT.en;
  const [archivoExtraBold, archivoRegular, markDataUri] = await Promise.all([
    loadArchivoWeight("Archivo-ExtraBold.ttf"),
    loadArchivoWeight("Archivo-Regular.ttf"),
    loadMarkDataUri(),
  ]);

  const fonts: NonNullable<ConstructorParameters<typeof ImageResponse>[1]>["fonts"] = [];
  if (archivoExtraBold) fonts.push({ name: "Archivo", data: archivoExtraBold, style: "normal", weight: 800 });
  if (archivoRegular) fonts.push({ name: "Archivo", data: archivoRegular, style: "normal", weight: 400 });

  // See the file header: this key must be omitted, not set to `undefined`.
  const fontFamilyStyle = fonts.length > 0 ? { fontFamily: "Archivo" } : {};

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: 80,
          background: OBSIDIAN,
          ...fontFamilyStyle,
        }}
      >
        <div style={{ display: "flex", flexDirection: content.isRtl ? "row-reverse" : "row" }}>
          {/* eslint-disable-next-line @next/next/no-img-element -- ImageResponse/Satori
              renders its own tree, not the DOM; next/image does not apply here. */}
          <img src={markDataUri} width={139} height={110} alt="" />
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: content.isRtl ? "flex-end" : "flex-start",
          }}
        >
          <div style={{ fontSize: 148, fontWeight: 800, color: NEAR_WHITE, letterSpacing: -4 }}>
            SCRIPE
          </div>
          <div style={{ fontSize: 40, fontWeight: 400, color: SIGNAL_LIME, marginTop: 20 }}>
            {content.tagline}
          </div>
        </div>
      </div>
    ),
    {
      ...size,
      fonts: fonts.length > 0 ? fonts : undefined,
    },
  );
}
